# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Gallery

# Model Form Field configuration
form: $/site/galleries/models/gallery/fields.yaml

# Model Class name
modelClass: Site\Galleries\Models\Gallery

# Default redirect location
defaultRedirect: site/galleries/galleries

# Create page
create:
    title: Create Gallery
    redirect: site/galleries/galleries/update/:id
    redirectClose: site/galleries/galleries

# Update page
update:
    title: Edit Gallery
    redirect: site/galleries/galleries
    redirectClose: site/galleries/galleries

# Preview page
preview:
    title: Preview Gallery
